### ISSUE TITLE
Can't install .jar (ami20190917a)

### ISSUE THREAD

**Issue by J-E-J-S** [petermr/ami-jars#1]
Attempted to install .jar in windows 10 with commandline with: 
java -jar ami20190917a-jar-with-dependencies.jar 

Output: 
A lot of readme type text ending with: 

log4j:WARN No appenders could be found for logger (org.contentmine.cproject.args.DefaultArgProcessor).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.NullPointerException
        at org.contentmine.cproject.args.DefaultArgProcessor.getOptionsWithMethod(DefaultArgProcessor.java:1100)
        at org.contentmine.cproject.args.DefaultArgProcessor.runMethodsOfType(DefaultArgProcessor.java:1077)
        at org.contentmine.cproject.args.DefaultArgProcessor.runRunMethodsOnChosenArgOptions(DefaultArgProcessor.java:1064)
        at org.contentmine.cproject.args.DefaultArgProcessor.runAndOutput(DefaultArgProcessor.java:1251)
        at org.contentmine.norma.Norma.run(Norma.java:31)
        at org.contentmine.norma.Norma.main(Norma.java:26)
------------------------------------------------------------------------------------------------------

ami-pdf remains an unrecognisable command 

Any ideas where I am going wrong with this installation?

**Comment by petermr** [comment]
I don't know why this has started happening . I got it as well

Not sure why it throws npe . It will normally just fail to output debug
statements
